BASE_URL="https://www.instagram.com/"
email_id="username"
password_id="password"
loginButton_id ="/html/body/div[2]/div/div/div[2]/div/div/div[1]/section/main/article/div[2]/div[1]/div[2]/form/div/div[3]"
kaydedilsinmi_id="/html/body/div[2]/div/div/div[2]/div/div/div[1]/div[1]/div[2]/section/main/div/div/div/div/div"
bildirimler_id="/html/body/div[2]/div[1]/div/div[2]/div/div/div/div/div[2]/div/div/div[3]/button[2]"
mesaj_id="/html/body/div[1]/div/div/div[2]/div/div/div[1]/div[1]/div[1]/div/div/div/div/div[2]/div[5]/div/div/div/span/div"
MesajGonder_id="/html/body/div[1]/div/div/div[2]/div/div/div[1]/div[1]/div[2]/section/div/div/div/div[1]/div/div[1]/div/div[3]/div/div/div/div/div[2]/div/div[1]/div/div/div/div"
mesajInput_id="/html/body/div[1]/div/div/div[2]/div/div/div[1]/div[1]/div[2]/section/div/div/div/div[1]/div/div[2]/div/div/div/div/div/div/div[2]/div/div/div[2]/div/div/div[2]/div/div[1]/p"
unuttumInput_id="cppEmailOrUsername"
unuttumbutton_id="//*[@id='loginForm']/a/span"
Baglantigonder_id="/html/body/div[2]/div/div/div[2]/div/div/div[1]/section/main/div[2]/div/div/div/div/div[5]/div"
emailInput_id="emailOrPhone"
kayiyolbutton_id="/html/body/div[2]/div/div/div[2]/div/div/div[1]/section/main/article/div[2]/div[2]/span/p/a"
adInput_id="fullName"
kullaniciad_id="username"
öneri_id="/html/body/div[2]/div/div/div[2]/div/div/div[1]/section/main/div/div/div[1]/div[2]/form/div[7]/div[1]/div/div"
öneri2_id="/html/body/div[2]/div/div/div[2]/div/div/div[1]/section/main/div/div/div[1]/div[2]/form/div[7]"
paswordInput_İd="password"
kayitolusturbutton_id="/html/body/div[2]/div/div/div[2]/div/div/div[1]/section/main/div/div/div[1]/div[2]/form/div[9]/div/button"
errorMessage_id="ssfErrorAlert"
errorMessage_text="Bu şifreyi tahmin etmek çok kolay. Lütfen yeni bir şifre oluştur."


errormessagee_text="Üzgünüz, şifren yanlıştı. Lütfen şifreni dikkatlice kontrol et."
errormessagee_id="/html/body/div[2]/div/div/div[2]/div/div/div[1]/section/main/div[2]/div/div/div[1]/div[3]/span"
loginbutton_id="//*[@id='loginForm']/div/div[3]/button"

